# Generated by Django 5.0.3 on 2024-03-29 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cantCalificaciones', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
