# Generated by Django 5.0.3 on 2024-03-30 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('metodoDePago', models.CharField(blank=True, max_length=100, null=True)),
                ('precioEnvio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precioTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechaPedido', models.DateTimeField(auto_now_add=True)),
                ('fechaPago', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('fechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('precioEnvio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producto')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Revisado',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
