# Generated by Django 5.0.3 on 2024-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='../../client/src/fotoDefault.png', null=True, upload_to=''),
        ),
    ]
